export enum FormFieldKey {
  Account = 'account',
  Amount = 'amount',
  Category = 'category',
  Date = 'date',
  Description = 'description',
  DueDate = 'dueDate',
  Facility = 'facility',
  IsInstallment = 'isInstallment',
  IsReadyToDeduct = 'isReadyToDeduct',
  IssueDate = 'issueDate',
  Note = 'note',
  ReceiptTaken = 'receiptTaken',
  ReminderDate = 'reminderDate',
  Status = 'status',
  Type = 'type',
  Website = 'website',
}
