export const FormFieldKey = {
  Account: 'account',
  Amount: 'amount',
  Attachments: 'attachments',
  Category: 'category',
  Date: 'date',
  Description: 'description',
  DueDate: 'dueDate',
  Facility: 'facility',
  IsInstallment: 'isInstallment',
  IsReadyToDeduct: 'isReadyToDeduct',
  IssueDate: 'issueDate',
  Note: 'note',
  ReceiptTaken: 'receiptTaken',
  ReminderDate: 'reminderDate',
  Status: 'status',
  Type: 'type',
  Website: 'website',
} as const;
